---
 
- name: "Run image {{ emqx_image_name }}:{{ emqx_image_tag }} as service {{ emqx_service_name }}"
  docker_container:
    name: "{{ emqx_service_name }}"
    image: "{{ emqx_image_name }}:{{ emqx_image_tag }}"
    published_ports:
      - "1883:1883"
      - "18083:18083"
    recreate: yes
    restart_policy: "{{ emqx_service_restart_policy }}"
    state: started
  register: emqx_service_launched
